import Providers from './Providers'
import Header from './components/Header'
import Tabs from './components/Tabs'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Movie App',
  description: 'Generated by create next app',
}

const Layout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header/>
          <Tabs/>
          {children}
        </Providers>
      </body>
    </html>
  )
}

export default Layout;
